version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    volumes:
      # Mount static files for development (optional)
      - ./static:/app/static
      - ./templates:/app/templates
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: flask-app-network
